[workspace]
members = [
  "common-rs",
  "fe-rs",
  "be-rs",
]

[patch.crates-io]
# wasm-bindgen = {path = "/Users/e/Documents/GitHub/wasm-bindgen"}
wasm-bindgen = {git = "https://github.com/trevyn/wasm-bindgen", branch = "getter_with_clone"}

[profile.release]
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
lto = true # Enable Link Time Optimization
opt-level = "s" # Optimize for size.
