name: ci

on: [workflow_dispatch, push]
      
env:
  CARGO_TERM_COLOR: always

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lycheeverse/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --headers="accept=text/html"

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  build:
    name: build ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11.0]
        rust: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}

      - run: npm install
        working-directory: 'fe-svelte'
        
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: npm run build
        working-directory: 'fe-svelte'

      - run: npm run svelte-check
        working-directory: 'fe-svelte'

      - run: cargo build --release
        working-directory: 'be-rs'

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.rust }}
          path: target/release/be-rs

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v2

      - id: vars
        run: echo "::set-output name=sha::$(echo $(date '+%y%m%d-%H%M')-${GITHUB_SHA:0:7})"

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.sha }}
          release_name: ${{ steps.vars.outputs.sha }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu-latest-stable/be-rs
          asset_name: be-rs
          asset_content_type: application/octet-stream